name    'dgrstl-jboss'
version '0.1.0'
source 'https://github.com/dgrstl/puppet-jboss.git'
author 'dgrstl'
license 'Apache License, Version 2.0'
summary 'Install and run JBoss products'
description 'Install and run JBoss products'
project_page 'https://github.com/dgrstl/puppet-jboss'
